### ISSUE TITLE
Email address request

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Network#13]
@cadecairos I need a new google group set up for network@mozillafoundation.org

**Comment by cadecairos** [comment]
@stephaniemcv I sent you an invite to the group. Let me know when you're in and I'll set you up as an owner.

**Comment by stephaniemcv** [comment]
I accept your invite!

**Comment by cadecairos** [comment]
you are now an owner!

**Comment by stephaniemcv** [comment]
Think I ran into a problem. I can't find a forwarding function in groups, so all the messages go into Desk.

**Comment by cadecairos** [comment]
How does desk get the emails?

**Comment by stephaniemcv** [comment]
the emails are forwarded from donate and askjoin

**Comment by cadecairos** [comment]
Does desk not have filtering tools?

**Comment by stephaniemcv** [comment]
Yes? But I'm not sure we're talking about the same thing.
