### ISSUE TITLE
Determine workflow for checking Network@ inbox

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Network#14]
Perhaps we need to identify one person to triage emails that come into this address?

@jessevondoom - what do you think? Could this be another role for the Editorial person? It's perhaps a little tangential to their role. I could do this to start, if there's not someone for whom this is an obvious task.

**Comment by jessevondoom** [comment]
Yeah I think this is ultimately an editorial thing and I agree we need someone checking it. That said, I do worry about just dumping it all on you.

Would it make sense to create a #mofo-network-monitor Slack channel for email notifications? We set up something similar at CASH and it made it easier to keep an eye on things. I could see it getting out of hand depending on throughput but maybe worth setting up until we have an editor putting eyes on it?

**Comment by hannahkane** [comment]
I think putting this into a Slack channel could be useful.

cc @stephaniemcv who might have some insight into how other teams/projects do this, and specifically how our Desk.com integration works.

**Comment by stephaniemcv** [comment]
Other teams have replybacks from emails forward into Desk.com. It's a case management system so each email that comes in creates a case. Each team has like their own little inbox and different people can log in and manage the cases. It also has the advantage of having things like macros, which are canned responses that you can pop into a reply with a few keystrokes or labels to tag messages and then run reports which allows you to see any issue or feedback trends.

Fundraising uses it to track and respond to donation issues. There's usually a lot of back and forth between us and the donor before a case is resolved as we usually need more info that what's initially provided. And you can easily escalate and assign cases to other people. 

Advocacy gets a lot of replybacks and it would be impossible to respond to them all. There's a much different setup for that to generate feedback reports. 

Considering the Network leaders are a smaller, more intimate group, my assumption is that your team could use Desk.com more like Fundraising.

**Comment by hannahkane** [comment]
@stephaniemcv - will replies to the initial email go to Desk.com? Do we need to do any configuration there, to set up routing workflows or anything?

@jessevondoom - maybe we start with Desk.com (if it's the default) and see how it goes?

**Comment by stephaniemcv** [comment]
@hannahkane no. I ran out of time to complete that setup. Filters and the Network inbox have not been set up yet.  A google group was created that I can add you too for triaging.

**Comment by hannahkane** [comment]
@stephaniemcv - please do add me to the google group. thanks!

**Comment by jessevondoom** [comment]
Yeah I think Desk offers us a lot more management potential for the workflow so let's start there. Setting up Slack notifications is as easy as adding another forwarding address to the incoming mailbox so we can do that if we like, but as long as there's a system in place that's easy/manageable I think we're great.

**Comment by arlissc** [comment]
@stephaniemcv - could you please add me to the google group as well as I'd like to track against the master email list.  thanks!

**Comment by hannahkane** [comment]
@stephaniemcv - is there another issue somewhere to track the Desk.com installation? If so, I'm going to close this one.

**Comment by stephaniemcv** [comment]
There is now! #22
