### ISSUE TITLE
How will core leaders continue to be added to the list?

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Network#15]
This came up on a call earlier this week.

@stephaniemcv @arlissc - technically speaking, is this as simple as people letting you know when they've identified new people to add to the list?

@jessevondoom @rtufail 270 folks & others - from a more programmatic perspective, do we have any action steps around how we'll identify core leaders moving forward? Will they need to be "onboarded" in any way?

**Comment by stephaniemcv** [comment]
Yes, for now they'll have to be manually added.

**Comment by arlissc** [comment]
@hannahkane - +1 to Steph.  To continue the current process I'd like them to come through/to me as I'm maintaining a master list (outside CRM) for tracking purposes and to gather info that could be loaded to CRM in the future.

**Comment by hannahkane** [comment]
Thanks @stephaniemcv and @arlissc.

@jessevondoom and @Lottarao  - in @mariapeeples [messaging doc](https://docs.google.com/document/d/16ZuHnPy8G22bz2h7T7MmDjr1e5pucSn-lbdMjWtQTEc/edit) I suggested we start an FAQ for staff, but I'm realizing that might be something you two already have going. I think these questions around "How do I invite new people to the leaders cohort?" should be thought through, if they haven't already been.

**Comment by hannahkane** [comment]
Closing this issue as we've answered the technical question. The more programmatic question lives on in the messaging document.
