### ISSUE TITLE
Finalize messaging guidelines / talking points

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Network#17]
@mariapeeples started drafting some [Messaging Guidelines and Talking Points](https://docs.google.com/document/d/16ZuHnPy8G22bz2h7T7MmDjr1e5pucSn-lbdMjWtQTEc/edit) and is looking for feedback, particularly in terms of whether any categories are missing.

@chrislarry33 @Lottarao @jessevondoom @xmatthewx  - please add your feedback to the doc!

**Comment by hannahkane** [comment]
Did we finalize this? I saw that a read-only version went out to program staff.

@jessevondoom - are you good with the final version?

**Comment by jessevondoom** [comment]
Yeah I'm good with it as it stands. My comments are all in and as long as we look at it as a living document I think we're good to go.

**Comment by hannahkane** [comment]
ok, closing this ticket
