### ISSUE TITLE
Dashboard for engagement metrics

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Network#21]
On the Wednesday call, Caroline mentioned that she's working with @vojtechmzl and @arlissc to build out a dashboard with user engagement metrics. I believe it will include something like:

- interactions with email
- website (traffic, actions, sign-ups)
- Pulse (posts, traffic)

Wondering if someone can share more details about the plan here, so others can have ambient awareness, if it's an appropriate time for that.

**Comment by vojtechsedlak** [comment]
Hi @hannahkane, we are indeed in the process of building out a Data Studio [dashboard](https://datastudio.google.com/open/0B5UMbl9u1_wQdTlJTDZFUS0wSGs), which aims to capture the following key metrics:

- Network website performance (sessions, pageviews and other usual suspects)
- Conversion journeys (form submissions, double opt-ins, onboarding experience)
- Email performance (opens, clicks, etc. + % of leaders who clicked through to the site)
- Pulse website performance (visits, submissions, etc.)

This is still a work in progress, but if you or anyone else have any suggestions, let me or Arliss know and we can incorporate it into the dashboard.

Thanks!

**Comment by hannahkane** [comment]
Thanks, @vojtechmzl.

cc @xmatthewx @taisdesouzalessa @sabrinang @alanmoo @gvn

**Comment by xmatthewx** [comment]
Thanks @vojtechmzl. Let me know how I can contribute. I'd be glad to discuss the metrics we're gathering in Pulse and on the site. I'm VERY excited to see all this info gathered in one place.

**Comment by vojtechsedlak** [comment]
Hi @xmatthewx, I would love to learn more about what kind of metrics we could pull in from Pulse. I already connected the Google Analytics property, but wondering where data is stored for submissions? Data Studio can connect to a variety of data sources, so hopefully we could automate the reporting process.

I would love to learn more about what you think would be useful to include on the dashboard from Pulse. Could we maybe set up a chat? Any ideas on the design aspect of things would also be appreciated. The dashboard is currently in an MVP format.

**Comment by alanmoo** [comment]
Maybe this would be useful: https://api.mozillapulse.org/entries/

**Comment by hannahkane** [comment]
The meeting the other day was useful! Since the dashboard is up and running, and iterations are being tracked elsewhere, I'm going to close this ticket.
