### ISSUE TITLE
Soft-launch email to core leaders - batch 1

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Network#4]
- [x] Complete RASCI doc (started [here](https://docs.google.com/document/d/1tF1QFDSBJ9U4tv6Es8_tpDp-EiZREB1XKSBvKuaLZQM/edit))
- [x] May 8: Finalize email copy for first Leader group
- [x] determine sender (Chris)
- [x] determine a from email address - network@
- [x] create an image for the email (https://github.com/mozilla/network/issues/403)
- [x] finalize leader file
- [x] upload leader file into SFDC
- [x] create sendable leader segment in SFMC
- [x] build email in SFMC
- [x] route email for QA
- [x] figure out how to let ppl unsubscribe to the core leader segment (#9)

**Comment by hannahkane** [comment]
@arlissc and @stephaniemcv - wasn't sure if I should include CRM-specific TODOs here, or if that would just be duplicative of what's in the CRM repo.

**Comment by stephaniemcv** [comment]
We're mostly documenting "enchilada" issues in the repo, so I'll add some tasks to the list.

**Comment by arlissc** [comment]
@hannahkane and @stephaniemcv  Just added the finalizing of the core leader file to the list above - feel free to reword if needs additional clarification re: batches

**Comment by stephaniemcv** [comment]
Which email do we want email replybacks and bounce backs to go to? I'm assuming @chrislarry33 you don't want your inbox full of out of office replies. We have askjoin@ for Advocacy or donate@ for fundraising, do we want a similar generic for Network?

**Comment by hannahkane** [comment]
@stephaniemcv - yes, please, can we have a generic. Could it be network@? (@chrislarry - does that sound alright to you?)

**Comment by hannahkane** [comment]
@chrislarry33 - does Network@ work for a generic email address?

**Comment by mariapeeples** [comment]
Network 50 language is in.

**Comment by hannahkane** [comment]
@stephaniemcv - have confirmed with @chrislarry33 and others that Network@ will work for a generic email address. We'll be working out a plan for who's going to monitor that inbox.

I've updated the email copy in the RASCI. The copy for the first send is final. Since we're now doing two emails, we have a draft copy for the second email as well, but it still needs some approvals.

**Comment by hannahkane** [comment]
Done!
