### ISSUE TITLE
Welcome email (autoresponder)

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Network#5]
- [x] May 8: Finalize initial [Welcome email](https://docs.google.com/document/d/1zvWhLa6oEkQ1bVxmU7zu8WJqJbQnV0pfp77ERm5NF18/edit) (for those who sign up on the site during the soft-launch) 
- [x] Update welcome email ( @stephaniemcv )

**Comment by hannahkane** [comment]
@stephaniemcv - can you please provide guidance about how we go about getting the autoresponder/Welcome email edited, once we have final copy? Thanks!

**Comment by stephaniemcv** [comment]
Once you have a post-soft-launch message approved, you'll have to hand it off to me so I can update the welcome journey. 

I'll need this initial copy to be final by 5/12 so I can set up the journey.

**Comment by hannahkane** [comment]
@stephaniemcv - [We have it](https://docs.google.com/document/d/1zvWhLa6oEkQ1bVxmU7zu8WJqJbQnV0pfp77ERm5NF18/edit)! There's a question for you in the doc, as well as a need to add Chris's title (maybe you can fill that in from other emails?)

Let me know if you want me to put this in the RASCI doc. Wasn't sure if it was needed, since it's an auto-response, rather than a mass send.

**Comment by hannahkane** [comment]
@stephaniemcv - do you have everything you need to update the journey?

**Comment by stephaniemcv** [comment]
I need a confirmation on the From Email. Is network@ the final decision?

**Comment by hannahkane** [comment]
@stephaniemcv - network@ is the final decision.

**Comment by hannahkane** [comment]
@stephaniemcv - please let me know when I can test and close this issue. Thanks!

**Comment by stephaniemcv** [comment]
You should be able to test the signup now. The expected experience is that you receive the double opt in confirm and then one of the two Network Welcomes.

The experience of replying back to the welcome is not finished yet (goes to a google group rather than a Desk inbox). Working to get that fixed, though not a blocker to the 5/23 send.

**Comment by hannahkane** [comment]
Worked as expected for me. Thanks, @stephaniemcv. Please close if you're comfortable with it.

**Comment by hannahkane** [comment]
Out of curiosity, are we able to change the Sender on that email? Wondering if "Chris Lawrence, Mozilla" would get a higher open rate than "Mozilla"?

**Comment by stephaniemcv** [comment]
Yes, we can change it. It would be easiest to do that when we update copy to post-soft launch so I can keep versions of the journey under control.

**Comment by hannahkane** [comment]
Thanks, @stephaniemcv. Can we close this ticket?
