### ISSUE TITLE
Clarify site feedback form vs. survey

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Network#8]
The site currently links to a [short form](https://docs.google.com/a/mozillafoundation.org/forms/d/e/1FAIpQLSdm8XPAiSXFTT5ILrEvHRZvMBHP6U2xtRFsTMaZPkYXBQ777A/viewform) to collect feedback. 270 has drafted a [similar survey](https://docs.google.com/document/d/1xVeaN_DbOMSLO74rKIT-ISOO20MmEcOuxrAH-RWlRCY/edit#). 

Can we clarify the different purposes? Do we need two separate surveys? What will be the delivery mechanisms for each?

**Comment by xmatthewx** [comment]
The short form was a placeholder by me. It should be replaced by 270 survey. 

Ask is set up and maybe ready. If you and Charissa can [get on board](https://github.com/MozillaFoundation/mofo-devops/issues/475#issuecomment-299585071), we can test it. Either by linking to the URL generated by Ask, or by embedding on a network site page. 

If not, we should update link or update the placeholder google form.

**Comment by xmatthewx** [comment]
I added to our 1-1 doc. We can figure out admin stuff then if we don't get to it sooner.

**Comment by hannahkane** [comment]
Will pursue Ask work, but in the meantime, @xmatthewx - could you give me or @charissalaisy edit access to the current form, so we can update it to match the 270 survey?

**Comment by xmatthewx** [comment]
Added you @hannahkane to [the form](https://docs.google.com/a/mozillafoundation.org/forms/d/1k0fjBABkEzz8Isg1XM4RfHIej6f8fwTZy5yDKOrMNRM/edit).  @charissalaisy should already have access.

**Comment by hannahkane** [comment]
Update for all:

@jessevondoom is working to get us access to a SurveyMonkey paid account so that @charissalaisy can build out the survey with conditional logic. Then we'll update the link on the site.

**Comment by hannahkane** [comment]
OK, we have a revised version of the survey up, so I'm closing this. We may want to iterate on the survey a bit, though, since it doesn't completely match what was originally drafted.
