### ISSUE TITLE
Allow people to unsubscribe from core leader segment

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Network#9]
Our plan is to send at least 5 emails to our group of identified core leaders (around 2500 people).

We should have a way for them to unsubscribe, without having to unsubscribe to all Mozilla Foundation emails. 

In addition to the standard unsubscribe link at the bottom of the email, we might want to offer a way for people to let us know they want to be removed from the particular segment. 

I can't think of a way to do this other than manual. Like, "If you'd rather not receive emails about the launch of the Network, please reply to this email" and then we manually remove them from the segment.

@stephaniemcv - do you know of a more automated way to do this?

cc @charissalaisy

**Comment by charissalaisy** [comment]
It might be easier to link to a one-field form that asks them to input their email address. That way we already have those emails in one spreadsheet so we can bulk unsubscribe in the backend.

I also think people might be more willing to input their email in a form than type in a blank email.

Any thoughts there?

**Comment by hannahkane** [comment]
@charissalaisy - are you thinking of embedding that form in the email, or having it linked from the email?

Also...I love your avatar. :)

**Comment by charissalaisy** [comment]
I was thinking of having it linked from the email, but embedding it is a great idea! I didn't know that was technically possible. 

Thanks! 270 makes me put a photo of myself on their platforms, so Github is where I rebel... ;)

**Comment by charissalaisy** [comment]
Also, sorry for delay. I need to turn GitHub notifications back on!

**Comment by stephaniemcv** [comment]
You can't embed a form in an email. Ok, technically you can code it, but it's not supported by most email clients, some will outright disable it, others will pop up a security alert. 

I would advocate that we direct them in the email to replyback saying they don't want to be part of the leadership cohort.  I think another link might detract from the main CTA.

**Comment by hannahkane** [comment]
@stephaniemcv - how would the actual unsubscribe happen?

**Comment by stephaniemcv** [comment]
I would remove them from the segment in SFMC.

**Comment by hannahkane** [comment]
So you should be a recipient of whatever email is the ReplyTo then, right?

**Comment by stephaniemcv** [comment]
If we do a generic email we can set it up to go into Desk.com and I can triage there. That's where replybacks to teach@, donate@ and askjoin@ land.

**Comment by hannahkane** [comment]
Is that what you were referencing in #4? If so, yes, that makes sense to me!

**Comment by stephaniemcv** [comment]
Yup, that's what I was talking about!

**Comment by hannahkane** [comment]
Got it! OK, I think we've figured it out. Added some suggested language to the copy doc. Closing this ticket.
